name: Data Workflow

on:
 push:
   branches:
     - main
 schedule:
    - cron: "0 0 * * *"
jobs:
 install_deps:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - name: Setup poetry
       run: |
         pipx install poetry
     - name: Setup Python
       uses: actions/setup-python@v3
       with:
        python-version: "3.10.6"
       

 fetch_data:
   needs: install_deps
   runs-on: ubuntu-latest
   outputs:
     sha_new: ${{steps.sha_new.outputs.SHA_NEW}}
   permissions:
     contents: write
   steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - name: Setup poetry
       run: |
         pipx install poetry
     - name: Setup Python
       uses: actions/setup-python@v3
       with:
         python-version: "3.10.6"
         token: ${{ secrets.TKN }}
     - uses: iterative/setup-dvc@v1
     - name: Setup Dagshub
       run: |
         dvc remote modify origin --local auth basic
         dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
         dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}
     - name: Setup git config
       run: |
         git config user.name "GitHub Actions Bot"
         git config user.email "qverdi@users.noreply.github.com"
     - name: Pull changes
       run: |
         git pull
         dvc pull
     - name: Fetch data
       run: poetry run fetch_data
     
     - name: Add data
       run: |
         dvc add data

     - uses: stefanzweifel/git-auto-commit-action@v4
       with:
         commit_message: Commit changed data

     - name: Push to dvc
       run: |
         dvc push
